# Generated by Django 4.2.2 on 2023-09-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name_plural': 'Cuentas'},
        ),
    ]
