# Generated by Django 4.2.2 on 2023-09-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_apertura',
            field=models.DateField(),
        ),
    ]
